# DuckDB config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True
default:
  target: dev
  outputs:
    dev:
      type: duckdb
      threads: 4
      path: "../data/data_catalog/mdsbox.duckdb"